use_frameworks!

platform :ios, '10.0'

target 'WZAnimation_Example' do
  pod 'WZAnimation', :path => '../'

  target 'WZAnimation_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 10.0
        if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
          end
        end
      end
    end
  end
  
end
